//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixtures.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fixtures.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF
        ///FF
        ///01
        ///00
        ///09
        ///00
        ///43
        ///72
        ///46
        ///69
        ///78
        ///74
        ///75.
        /// </summary>
        internal static string FirstMatchHeader {
            get {
                return ResourceManager.GetString("FirstMatchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) &lt;year&gt; &lt;copyright holders&gt;
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///Th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01
        ///80
        ///00
        ///00
        ///00
        ///00
        ///FF
        ///34
        ///77
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///CD
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///.
        /// </summary>
        internal static string MatchTemplate {
            get {
                return ResourceManager.GetString("MatchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FC GEN,14,4
        ///#OD GEN,13,1
        ///#Overseas League (T20 GEN),8,1
        ///#T20 GEN,15,1
        ///Big Bash League,6,1
        ///Clydesdale Bank 40,2,1
        ///Commonwealth Bank Series,0B,1
        ///County Championship,0,4
        ///Friends Life T20,3,1
        ///Indian Premier League,7,1
        ///One Day Friendly,0F,1
        ///One Day International,0D,1
        ///Ryobi One Day Cup,5,1
        ///Sheffield Shield,4,4
        ///T20 International,12,1
        ///Test Match,0C,5
        ///Three Day Friendly,0E,3
        ///University Match,11,3
        ///World Cup,9,1
        ///World T20,0A,1
        ///.
        /// </summary>
        internal static string MatchTypes {
            get {
                return ResourceManager.GetString("MatchTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia,002B
        ///Bangladesh,33
        ///England,002C
        ///India,002D
        ///New Zealand,002E
        ///Pakistan,002F
        ///South Africa ,30
        ///Sri Lanka,31
        ///West Indies,32
        ///Zimbabwe,34
        ///Australia (World Cup),018C
        ///Bangladesh (World Cup),189
        ///England (World Cup),185
        ///India (World Cup),018D
        ///Ireland (World Cup),018A
        ///Kenya (World Cup),018B
        ///Netherlands (World Cup),191
        ///New Zealand (World Cup),018E
        ///Pakistan (World Cup),188
        ///South Africa  (World Cup),186
        ///Sri Lanka (World Cup),187
        ///UAE (World Cup),192
        ///West Indies (World Cup),018F
        ///Zimbabwe (Wo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
    }
}
