//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fixtures.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fixtures.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF
        ///FF
        ///01
        ///00
        ///09
        ///00
        ///43
        ///72
        ///46
        ///69
        ///78
        ///74
        ///75.
        /// </summary>
        internal static string FirstMatchHeader {
            get {
                return ResourceManager.GetString("FirstMatchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) &lt;year&gt; &lt;copyright holders&gt;
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///Th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01
        ///80
        ///00
        ///00
        ///00
        ///00
        ///FF
        ///34
        ///77
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///01
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///00
        ///.
        /// </summary>
        internal static string MatchTemplate {
            get {
                return ResourceManager.GetString("MatchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FC GEN,14,4
        ///#OD GEN,13,1
        ///#Overseas League (T20 GEN),8,1
        ///#T20 GEN,15,1
        ///Big Bash League,6,1
        ///Clydesdale Bank 40,2,1
        ///Commonwealth Bank Series,0B,1
        ///County Championship,0,4
        ///Friends Life T20,3,1
        ///Indian Premier League,7,1
        ///One Day Friendly,0F,1
        ///One Day International,0D,1
        ///Ryobi One Day Cup,5,1
        ///Sheffield Shield,4,4
        ///T20 International,12,1
        ///Test Match,0C,5
        ///Three Day Friendly,0E,3
        ///University Match,11,3
        ///World Cup,9,1
        ///World T20,0A,1
        ///.
        /// </summary>
        internal static string MatchTypes_2012 {
            get {
                return ResourceManager.GetString("MatchTypes_2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Bash League,06,1
        ///Champions Trophy,0E,1
        ///Clydesdale Bank 40,02,1
        ///County Championship,00,4
        ///Friends Life T20,03,1
        ///Indian Premier League,07,1
        ///One Day Friendly,10,1
        ///One Day International,0D,1
        ///Ryobi One Day Cup,05,1
        ///Sheffield Shield,04,4
        ///T20 International,13,1
        ///Test Match,0C,5
        ///Three Day Friendly,0F,3
        ///ODI Triangular,0B,1
        ///University Match,12,3
        ///World Cup,09,1
        ///World T20,0A,1
        ///
        ///.
        /// </summary>
        internal static string MatchTypes_2013 {
            get {
                return ResourceManager.GetString("MatchTypes_2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Bash League,06,1
        ///Champions Trophy,0E,1
        ///Royal London One Day Cup,02,1
        ///County Championship,00,4
        ///Natwest T20 Blast,03,1
        ///Indian Premier League,07,1
        ///One Day Friendly,10,1
        ///One Day International,0D,1
        ///Ryobi One Day Cup,05,1
        ///Sheffield Shield,04,4
        ///T20 Friendly,1A,1
        ///T20 International,13,1
        ///Test Match,0C,5
        ///Three Day Friendly,0F,3
        ///ODI Triangular,0B,1
        ///University Match,12,3
        ///World Cup,09,1
        ///World T20,0A,1
        ///.
        /// </summary>
        internal static string MatchTypes_2014 {
            get {
                return ResourceManager.GetString("MatchTypes_2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus One Day Cup,05,1
        ///Aus Tri-Series,14,1
        ///Aus Twenty Over Trophy,06,1
        ///Champions Trophy,17,1
        ///County Championship,00,4
        ///Eng One Day Cup,02,1
        ///Eng Twenty Over Trophy,03,1
        ///Ind One Day Cup,08,1
        ///Ind Twenty Over Trophy,09,1
        ///Indian Premier League,0A,1
        ///Nzl One Day Cup,0C,1
        ///Nzl Twenty Over Trophy,0D,1
        ///One Day Friendly,19,1
        ///One Day International,16,1
        ///Plunket Shield,0B,4
        ///Ranji Trophy,07,4
        ///Sheffield Shield,04,4
        ///Sunfoil Series,0E,4
        ///Test Match,15,5
        ///Three Day Friendly,18,3
        ///Twenty20 International,1C,1
        ///Univ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MatchTypes_2016 {
            get {
                return ResourceManager.GetString("MatchTypes_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus One Day Cup,06,1
        ///Aus Tri-Series,FE,1
        ///Aus Twenty Over Trophy,07,1
        ///Bangladesh Premier League,1D,1
        ///Caribbean Premier League,15,1
        ///Champions Trophy,17,1
        ///County Championship,00,4
        ///Eng One Day Cup,02,1
        ///Eng Twenty Over Trophy,03,1
        ///Eng 100 Ball Trophy,04,1
        ///Ind One Day Cup,09,1
        ///Ind Twenty Over Trophy,0A,1
        ///Indian Premier League,0B,1
        ///Nzl One Day Cup,0D,1
        ///Nzl Twenty Over Trophy,0E,1
        ///One Day Friendly,27,1
        ///One Day International,24,1
        ///Pak One Day Cup,18,1
        ///Pakistan Twenty Over Trophy,19,1
        ///Pakistan Super [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MatchTypes_2021 {
            get {
                return ResourceManager.GetString("MatchTypes_2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia,002B
        ///Bangladesh,33
        ///England,002C
        ///India,002D
        ///New Zealand,002E
        ///Pakistan,002F
        ///South Africa ,30
        ///Sri Lanka,31
        ///West Indies,32
        ///Zimbabwe,34
        ///Australia (World Cup),018C
        ///Bangladesh (World Cup),189
        ///England (World Cup),185
        ///India (World Cup),018D
        ///Ireland (World Cup),018A
        ///Kenya (World Cup),018B
        ///Netherlands (World Cup),191
        ///New Zealand (World Cup),018E
        ///Pakistan (World Cup),188
        ///South Africa  (World Cup),186
        ///Sri Lanka (World Cup),187
        ///UAE (World Cup),192
        ///West Indies (World Cup),018F
        ///Zimbabwe (Wo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teams_2012 {
            get {
                return ResourceManager.GetString("Teams_2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia,002B
        ///Bangladesh,0033
        ///England,002C
        ///India,002D
        ///New Zealand,002E
        ///Pakistan,002F
        ///South Africa ,0030
        ///Sri Lanka,0031
        ///West Indies,0032
        ///Zimbabwe,0034
        ///Australia (World Cup),018C
        ///Bangladesh (World Cup),0189
        ///Canada (World Cup),0191
        ///England (World Cup),0185
        ///India (World Cup),018D
        ///Namibia (World Cup),0192
        ///New Zealand (World Cup),0188
        ///Pakistan (World Cup),0187
        ///Scotland (World Cup),018B
        ///South Africa  (World Cup),0186
        ///Sri Lanka (World Cup),018E
        ///UAE (World Cup),018A
        ///West Indies (World Cup),018 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teams_2013 {
            get {
                return ResourceManager.GetString("Teams_2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia,002B
        ///Bangladesh,0033
        ///England,002C
        ///India,002D
        ///New Zealand,002E
        ///Pakistan,002F
        ///South Africa,0030
        ///Sri Lanka,0031
        ///West Indies,0032
        ///Zimbabwe,0034
        ///Scotland,00B0
        ///Australia (World Cup),01E9
        ///Bangladesh (World Cup),01ED
        ///England (World Cup),01F0
        ///India (World Cup),01EA
        ///New Zealand (World Cup),01F2
        ///Pakistan (World Cup),01EB
        ///South Africa (World Cup),01F1
        ///Sri Lanka (World Cup),01EC
        ///West Indies (World Cup),01F3
        ///Zimbabwe (World Cup),01F4
        ///Associate #1 (World Cup),01EE
        ///Associate #2 (World Cup),0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teams_2014 {
            get {
                return ResourceManager.GetString("Teams_2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia,002b
        ///Bangladesh,0033
        ///England,002c
        ///India,002d
        ///New Zealand,002e
        ///Pakistan,002f
        ///South Africa,0030
        ///Sri Lanka,0031
        ///West Indies,0032
        ///Zimbabwe,0034
        ///Australia CT,0209
        ///Bangladesh CT,0210
        ///England CT,020e
        ///India CT,020a
        ///New Zealand CT,020b
        ///Pakistan CT,020f
        ///South Africa CT,020d
        ///Sri Lanka CT,020c
        ///Associate #1 WT20,01fa
        ///Associate #2 WT20,01fb
        ///Associate #3 WT20,01fc
        ///Associate #4 WT20,01fe
        ///Associate #5 WT20,0200
        ///Associate #6 WT20,01ff
        ///Australia WT20,0322
        ///Bangladesh WT20,01f9
        ///England WT20,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teams_2016 {
            get {
                return ResourceManager.GetString("Teams_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derbyshire T20,0001
        ///Durham T20,0002
        ///Essex T20,0003
        ///Glamorgan T20,0004
        ///Gloucestershire T20,0005
        ///Hampshire T20,0006
        ///Kent T20,0007
        ///Lancashire T20,0008
        ///Leicestershire T20,0009
        ///Middlesex T20,000A
        ///Northamptonshire T20,000B
        ///Nottinghamshire T20,000C
        ///Somerset T20,000D
        ///Surrey T20,000E
        ///Sussex T20,000F
        ///Warwickshire T20,0010
        ///Worcestershire T20,0011
        ///Yorkshire T20,0012
        ///Australia,002B
        ///England,002C
        ///India,002D
        ///New Zealand,002E
        ///Pakistan,002F
        ///South Africa,0030
        ///Sri Lanka,0031
        ///West Indies,0032
        ///Banglades [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Teams_2021 {
            get {
                return ResourceManager.GetString("Teams_2021", resourceCulture);
            }
        }
    }
}
